✨ GroupUserコンポーネント作成
tuyotuyo-engineer/prj-calendar pull request #6
Opened 2024-02-05 11:10 UTC by tomoya092013

## ブランチ
- main
  - feature/group_component

## 結果
- GroupUser
#### url : http://localhost:6006/?path=/docs/group-group--docs

https://github.com/tuyotuyo-engineer/prj-calendar/assets/78564855/1b25c04a-87a7-47fc-8a45-fa22ebc33376

2024-02-06 16:30 UTC, tzptzptzptzptzp commented
Discordに書かれているので大丈夫だと思いますが、コミットは細かく分けていただけると嬉しいです！
例：
🔧 storybook設定ファイルを更新
🏷️ userListの型を定義
✨ Groupコンポーネントを実装
　　　　　　　　　　　　　　など

2024-02-07 13:12 UTC, kenta0603 commented on frontend/src/features/group/components/atoms/AddGroupUser/AddGroupUser.atom.tsx
> +  title = '＋ Add Group User',
`+`は将来的にSVGにするといいかも！

2024-02-07 13:22 UTC, kenta0603 commented on frontend/src/features/group/components/organisms/Group.organism.tsx
> +  };
僕はこうゆうパッと見て何してるか分からない所や処理内容を追わないと理解するのに時間がかかる所はコメントをするようにしています！
自分自身の為でもあり今回はチームメイトの為でもあります！

2024-02-07 13:23 UTC, kenta0603 commented on frontend/src/features/group/components/organisms/Group.organism.tsx
> +        backgroundColor: 'rgba(255, 255, 255, 0.25)',
カラーの指定方法も統一した方がいいかも！皆の意見を聞きたい

2024-02-12 16:08 UTC, tzptzptzptzptzp requested changes

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/atoms/AddGroupUser/AddGroupUser.atom.tsx
動作的にはボタンと同じなのでButtonコンポーネントにvariant: none（スタイルなし）を追加してそちらを利用していただきたいです！
スタイルはclassName="text-right"をプロップスで渡すのみで大丈夫です！（デフォルト文字スタイルが16px, #444）
また、divにonClickを定義するのはあまり良くないみたいです！
https://zenn.dev/tm35/articles/64eac4c0570c4d

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/atoms/GroupUser/GroupUser.atom.tsx
> +    <div className="flex flex-row items-center  gap-2.5 h-8">
flexはデフォルトでflex-direction: rowだと思うので、flex-rowは不要です！
gapに関しては10pxなのでgap-4(1rem)となります！
フォントサイズが18px、line-height: 1;なので高さの指定は不要です！
スペース２つ分空いてるのも気になります！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/atoms/GroupUser/GroupUser.atom.tsx
> +        className="w-6.5 h-6.5 accent-text cursor-pointer border-2 border-blue-gray-200"
border-2が当たっているのでstyle={{ borderWidth: '2px' }}は不要です！
w-6.5, h-6.5は存在しません。今回だと16pxなのでw-[1.6rem] h-[1.6rem]になります！
ボーダーのカラーもborder-textでOKです！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/atoms/GroupUser/GroupUser.atom.tsx
> +      <div className=" text-text text-3xl">{name}</div>
divではなくlabelでお願いしたいです！
以下のようにすることで文字クリックでも切り替え可能になります。
｜<input type="checkbox" id="好きなID">
｜<label for="好きなID">サンプル</label>
"好きなID"部分は同じIDをいれる必要があるので、プロップスでインデックスなどを受け取りuser-0{index}などとして、動的に紐づけられるようにする必要があります！
https://denblog.info/archives/2453

また、tailwindのfont-size(text-3xl)などはline-heightも合わせて指定されるため、
今回の場合だとtext-[1.8rem]でお願いします！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/organisms/Group.organism.tsx
基本的にストーリーブック上ではなくページ内にコンポーネントを配置して開発をお願いしたいです！
（ストーリーブック上だと微妙にスタイルのブレが生じる）
　→https://gyazo.com/e7e4eca5e7e424a9c10402c52f92ef85
　→https://gyazo.com/3c316d1e91521e5a2f18712a8bcf9821

useStateは"use client"を付けないとエラーが発生します！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/organisms/Group.organism.tsx
> +  const [userList, setUserList] = useState<GroupUserType[]>(initUserList);
プロップスで受け取ったinitUserListをuseStateの初期値に入れているのが違和感があります！
恐らくAPIから取得されたuserListでStateが更新されると思うので、初期値は[]で良いのではないでしょうか？

また、こちらでもモックを用意しuseEffectなどで値をStateに入れるほうが、実際に繋ぎ込みをする時に差分が少なくなるかと思います！

const mockData = [
  {
    name: 'User Name',
    selected: true,
  },
  ....
]

  useEffect(() => {
    setUserList(mockData);
  }, [mockData])
とかですかね！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/organisms/Group.organism.tsx
> +      }}
"section-base flex flex-col gap-8 w-[32rem] rounded-[2.5rem]" でOKです！
高さ指定しなくてOKです！min-height, max-heightは設定しても良いかも！

言うの忘れてて申し訳ないのですが、セクションの共通クラスを作成しているのでこちら当てていただくだけでOKです！
.section-base {
  border: 3px solid white;
  background-color: rgba(255, 255, 255, 0.25);
}
box-shadowは入れ忘れです、、、あとで入れておきます！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/organisms/Group.organism.tsx
> +      <div className="text-text text-3xl">{groupName}</div>
divではなく、h2, h3, p あたりが良いかもしれません！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/organisms/Group.organism.tsx
> +      <div className="h-52 overflow-y-auto">
高さ指定不要です！
overflow-y-scrollで良いかと思います！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/organisms/Group.organism.tsx
> +        <div className="flex flex-col gap-[1.7rem] ml-4 h-52">
gap-8 高さ指定不要です！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/organisms/Group.organism.tsx
> +      <AddGroupUser onClick={addGroupUser} />
Buttonを使用した場合：
`<Button className="text-right" onClick={addGroupUser} variant='none'>＋ Add Group User</Button>`

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/organisms/Group.stories.ts
業務を想定した名称、命名でお願いします😇

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/atoms/GroupUser/GroupUser.atom.tsx
> +        className="w-6.5 h-6.5 accent-text cursor-pointer border-2 border-blue-gray-200"
inputも共通atomとして切り出したいです！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/atoms/AddGroupUser/AddGroupUser.atom.tsx
既にvariantでnoneを受け取れるように実装していたので、classNameだけ渡すのみでOKです！

2024-02-18 05:41 UTC, kenta0603 commented on frontend/src/features/group/components/atoms/AddGroupUser/AddGroupUser.atom.tsx
> +  title = '＋ Add Group User',
これは一旦保留

2024-02-18 06:11 UTC, kenta0603 commented on frontend/src/features/group/components/atoms/GroupUser/GroupUser.atom.tsx
> +      <div className=" text-text text-3xl">{name}</div>
修正方法の認識合っていますかね？

2024-02-18 06:13 UTC, kenta0603 commented on frontend/src/features/group/components/organisms/Group.organism.tsx
`'use client'`は追加しました！
> 基本的にストーリーブック上ではなくページ内にコンポーネントを配置して開発をお願いしたいです！

僕のPRマージ後の方が良いと思ったので保留にしています！

2024-02-18 06:23 UTC, kenta0603 commented on frontend/src/features/group/components/organisms/Group.stories.ts
すみません！ここの適切な命名がよく分からないです！
AddGroupとかですかね？
ここお任せ致します！

2024-02-20 15:16 UTC, tzptzptzptzptzp requested changes

2024-02-20 15:16 UTC, tzptzptzptzptzp commented on frontend/src/components/atoms/CheckBox/CheckBox.atom.tsx
> +};
atomsの型はfrontend/src/components/atoms/atom.type.tsに定義しているので、そちらにお作りいただくか、コンポーネント内で作成するのであればButton.atom.tsxもコンポーネント内で型を定義するように統一したいです！

2024-02-20 15:16 UTC, tzptzptzptzptzp commented on frontend/src/components/atoms/CheckBox/CheckBox.atom.tsx
> +    />
borderなどのスタイルが当たっていないようです！
デフォルトのスタイルが適用されているのでそちらをリセットする必要があるのかもしれません。
ここらへんが面倒だからアイコンで実装するケースがあるのかもしれませんね😇（ブラウザによる差異もなくなる）
https://renkosaka.com/customize-checkbox/

2024-02-20 15:16 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/atoms/AddGroupUser/AddGroupUser.atom.tsx
> +    </Button>
変更ありがとうございます！
Group.organism.tsxで直接Buttonを呼び出しているのと同じになるので、こちらのコンポーネントは削除で大丈夫だと思います！

2024-02-20 15:33 UTC, tzptzptzptzptzp requested changes

2024-02-20 15:33 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/organisms/Group.organism.tsx
> +      }}
こちらも修正お願いします！
```
<div className="section-base flex flex-col gap-8 justify-between relative w-[32rem] rounded-[2.5rem] p-12">
  <p className="text-text text-[2rem]">{groupName}</p>
  <div className="overflow-y-scroll">
```
で大丈夫だと思います！

2024-02-20 15:33 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/organisms/Group.organism.tsx
> +  const [userList, setUserList] = useState<GroupUserType[]>(initUserList);
こちらも修正をお願いします！
userListの初期値は空配列でOKです！
[userList, setUserList] = useState<GroupUserType[]>([]);

useEffectで擬似的にデータを取得してステートを更新する形が良いと思います！

2024-02-20 15:36 UTC, tzptzptzptzptzp commented on frontend/src/features/group/components/atoms/GroupUser/GroupUser.atom.tsx
> +      <div className=" text-text text-3xl">{name}</div>
@kenta0603 
<label>の中に<div>を置くのは良くないみたいなので、<span>に変更していただけますか🙇！

2024-02-24 06:03 UTC, kenta0603 commented on frontend/src/features/group/components/organisms/Group.stories.ts
対応しました！

2024-02-25 09:02 UTC, kenta0603 commented on frontend/src/components/atoms/CheckBox/CheckBox.atom.tsx
> +    />
ここ僕の環境だと確認出来ないのでお任せしても良いですか？
もしくはアイコンで実装するのであれば`feature/chatCompornent`のブランチでsvgのライブラリ入れているのでマージ後に対応します！

2024-02-26 12:56 UTC, tzptzptzptzptzp approved these changes

2024-02-26 13:24 UTC, tzptzptzptzptzp commented
修正お疲れ様でした！
マージしていただいて大丈夫です！
ありがとうございました🙇

2024-03-03 06:13 UTC, merged