Feature/chat component
tuyotuyo-engineer/prj-calendar pull request #8
Opened 2024-02-10 08:15 UTC by kenta0603

## Chatコンポーネント作成

### 概要
UIのみの実装につき動的な変化はしない

### イメージ
![image](https://github.com/tuyotuyo-engineer/prj-calendar/assets/108261958/9a68886e-f311-425e-bf71-43a6ac1c8520)

2024-02-12 16:08 UTC, tzptzptzptzptzp requested changes

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/Chat.tsx
> +const dateTime = `2024.02.10`;
オブジェクトにまとめた方が良い気がしました！
const mockData = {
  usermame: '山田 太郎',
  datetime: '2024-12-25 12:00:00',
  message: '今日はPHPの勉強をします!',
};

日付、時間はそれぞれ以下で取得できます！
const dateObj: Date = new Date(mockData.datetime);

// 日付を YYYY.MM.DD 形式で取得
const formattedDate: string = `${dateObj.getFullYear()}.${dateObj.getMonth() + 1 < 10 ? '0' + (dateObj.getMonth() + 1) : dateObj.getMonth() + 1}.${dateObj.getDate() < 10 ? '0' + dateObj.getDate() : dateObj.getDate()}`;

// 時間を HH:MM 形式で取得
const formattedTime: string = `${dateObj.getHours() < 10 ? '0' + dateObj.getHours() : dateObj.getHours()}:${dateObj.getMinutes() < 10 ? '0' + dateObj.getMinutes() : dateObj.getMinutes()}`;

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/Chat.tsx
> +export default Chat;
コンポーネントは named export でお願いします！
`export const Chat = () => {`

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/Chat.tsx
> +    </div>
セクションの共通クラスを作成しているのでこちらを当てていただければOKです！
今回の場合は以下になります！
`<div className='section-base flex flex-col w-[32rem] px-4 pt-8 pb-4 rounded-[25px]'>`

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/Chat.tsx
> +    </div>
box-shadowは当て忘れなので当てておきます。
角丸はコンポーネントごとに値が変わるので、コンポーネント側で指定してください！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/atoms/ChatDate.tsx
> +    </div>
分かりづらくて申し訳ないのですが、背景色と角丸が当たっています！
こちらご調整いただけると嬉しいです！
https://gyazo.com/11674655b49639a1ad4f2d2cd2b868cb

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/molecules/ChatMessage.tsx
> +};
Propsでuserを受け取り、デザインを分岐すればchatMessageとchatMyMessageをひとつにまとめられるのではないかと思いました！
変更差異が少ない場合は`className={user ? '' : ''}`、
ごちゃごちゃするようであれば、module.scssを使用していただければと思います！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/molecules/ChatMessage.tsx
> +};
Flexでスタイリングしている場合、`flex-row-reverse flex-col-reverse`でそれぞれ逆順にできます！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/molecules/ChatUserHead.tsx
> +    </div>
チャット内の要素は全てmargin-bottomで余白調整した方が良い気がします！
このコンポーネントのマージンをmb-2、chatDateにもmb-2を指定していただければ良いかと思います！

2024-02-12 16:08 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/molecules/MessageForm.tsx
> +      </button>
Buttonコンポーネントがあるのでそちらを使ってください！
frontend/src/components/atoms/Button/Button.atom.tsx

2024-02-13 13:38 UTC, kenta0603 commented on frontend/src/features/chat/components/Chat.tsx
> +const dateTime = `2024.02.10`;
JSで時間を扱うのはdayjsが主流ぽいので時間の部分はdayjsで対応しました！

2024-02-13 13:57 UTC, kenta0603 commented on frontend/src/features/chat/components/Chat.tsx
> +    </div>
> 角丸はコンポーネントごとに値が変わるので、コンポーネント側で指定してください！
`<div className='section-base flex flex-col w-[32rem] px-4 pt-8 pb-4 rounded-[25px]'>`で問題ないですか？

2024-02-13 13:59 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/Chat.tsx
> +    </div>
OKです🙆！

2024-02-21 13:48 UTC, tzptzptzptzptzp requested changes

2024-02-21 13:48 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/chat.types.ts
> +};
命名についてTypeかPropsかどちらかに統一して欲しいです！
ファイル名がtype.tsなのでTypeに統一で大丈夫かと思います！

2024-02-21 13:48 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/Chat.tsx
> +    </div>
モックを利用してUIを実装する際は実際の利用シーンを想定しながら実装していただければと思います！
データ量が多くなった場合レイアウトが崩れてしまうので、このあたりも調整をお願いします！
データの繋ぎ込み時はUIの調整は微調整程度にとどめた方が工数のズレなども発生しずらいと思います！
https://gyazo.com/57f99f4d4c99ac3e3b8ecc5f264facd6

2024-02-21 13:48 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/atoms/ChatDate.tsx
> +    </div>
デザイン上は高さ15px、実装は高さ20pxと若干差異があります！
できるだけデザインに合わせた実装をしていただけると嬉しいです！
`<div className='flex justify-center items-center h-6 rounded-full bg-white/50 max-w-max mx-auto mb-2 px-4'>`

2024-02-21 13:48 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/molecules/ChatMessage.tsx
> +};
ChatMessage.tsxは一つのチャットのコンポーネントとし、
ChatHistoryなどのコンポーネントでラッピングしmapした方が良いかな、と感じました。
https://gyazo.com/ae63f1338ba29f92321a24a054e6562f
```
ChatHistory.tsx
export const ChatHistory = ({ mockData }: { mockData: ChatMessageProps[] }) => {
  return (
    <div className='チャット欄のレイアウト'>
      {mockData.map((data, i) => (
        <ChatMessage mockData={mockData} />
      ))}
    </div>
  );
};
```

2024-02-21 13:48 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/molecules/ChatMessage.tsx
> +            >
クラスの分岐がごちゃごちゃしている＋map内で毎回処理されると無駄が多いように感じます！
以下のように実装するとスマートかもしれません。
```
ChatMessage.tsx
<div className={clsx([styles.wrapper, styles[data.userType]])}>

ChatMessage.module.scss
.wrapper {
  display: flex;
  align-items: center;
  margin-bottom: 0.8rem;

  &.self {
    flex-direction: row-reverse;
  }

  &.other {
    flex-direction: row;
  }
}
```

2024-02-21 13:48 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/molecules/ChatMessage.tsx
> +};
また、ディレクトリ構成については現状
`/components/atoms/Button/Button.atom.tsx`となっているので、
/featuresは以下も以下のような形にしていただければと思います！
`/features/chat/components/molecules/ChatMessage/ChatMessage.molecule.tsx`

2024-02-21 13:48 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/molecules/ChatUserHead.tsx
> +    </div>
アイコンと名前の間にgap: 5px空けています！

2024-02-21 13:48 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/molecules/ChatMessage.tsx
> +          </Fragment>
`<p className='text-[10px] text-light-gray mx-4'>{formattedTime}</p>`について、
デザイン上は中央ではなくやや下に配置しているので合わせていただけると嬉しいです！
細かくてすみません🙇

2024-02-21 13:48 UTC, tzptzptzptzptzp commented on frontend/src/features/chat/components/molecules/MessageForm.tsx
> +    </div>
<div>でなく<form>でラップしていただければと思います！

2024-02-26 13:23 UTC, tzptzptzptzptzp approved these changes

2024-02-26 13:26 UTC, tzptzptzptzptzp commented
@kenta0603 
修正お疲れ様でした！
いくつかこちらで修正しているので確認いただけると嬉しいです！
確認後、マージしていただいて大丈夫です！
ありがとうございました🙇

2024-03-03 06:27 UTC, merged