Feature/tag edit button
tuyotuyo-engineer/prj-calendar pull request #9
Opened 2024-02-10 08:51 UTC by kenta0603

### スケジュールタグ設定ボタンを作成
`feature/chat-component`から切ったブランチ

### イメージ
![image](https://github.com/tuyotuyo-engineer/prj-calendar/assets/108261958/a723dc69-f80c-4322-94e1-2be654d13697)

2024-02-13 13:17 UTC, tzptzptzptzptzp requested changes

2024-02-13 13:17 UTC, tzptzptzptzptzp commented on frontend/src/app/layout.tsx
> +      <body className={`${inter.className} font-noto-sans-jp`}>{children}</body>
フォントの指定は next/font を使用していただいた方が良いと思います！
import { Noto_Sans_JP } from 'next/font/google';
const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] });
<body className={notoSansJP.className}>
現状上書きされてしまう時もあります！
https://gyazo.com/ad5657944ba2b7055eb364539da268b4

2024-02-13 13:17 UTC, tzptzptzptzptzp commented on frontend/src/components/atoms/TagEditButton/TagEditButton.tsx
> +}
こちらもButtonコンポーネントの流用でOKかなと思います！
新たにvariantを作成していただきデザインを当てていただければと思います！
また、margin-bottomではなく親コンポーネントでgapを利用して余白調整していただきたいです！
frontend/src/components/atoms/Button/Button.atom.tsx

2024-02-13 13:17 UTC, tzptzptzptzptzp commented on frontend/tailwind.config.ts
> +      },
next/font で対応可能であれば削除でOKです！

2024-02-21 14:06 UTC, tzptzptzptzptzp requested changes

2024-02-21 14:06 UTC, tzptzptzptzptzp commented on frontend/src/app/layout.tsx
> +const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] });
`const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] });`こちらについて
以下参照し最適な設定にしていただければと思います🙇
https://zenn.dev/yuro/articles/433b938eea9cd5

2024-02-21 14:06 UTC, tzptzptzptzptzp commented on frontend/src/components/atoms/TagEditButton/TagEditButton.tsx
> +};
```
<div className='flex flex-col w-[32rem] bg-green-300 gap-16'>
  <TagEditButton />　//←ここに直接 <Button variant='tagEdit' onClick={() => }> を配置する
  <Chat />
</div>
```
TagEditButton.tsxは削除してしまってOKです！

2024-02-21 14:06 UTC, tzptzptzptzptzp commented on frontend/src/components/atoms/TagEditButton/TagEditButton.tsx
> +};
frontend/src/components/atoms/Button/Button.module.scssに
`.tagEdit {}`を作成していただければ大丈夫です！
不明点あれば聞いてください🙇！

2024-02-25 10:47 UTC, kenta0603 commented on frontend/src/app/layout.tsx
> +});
@tzptzptzptzptzp 
修正方法合っていますかね？

2024-02-26 13:42 UTC, tzptzptzptzptzp commented on frontend/src/app/layout.tsx
> +});
@kenta0603 
遅れてすみません、、、
修正内容問題ないです！
ありがとうございます！

2024-02-26 13:43 UTC, tzptzptzptzptzp commented
@kenta0603 
修正お疲れ様でした！
こちらも少しだけ修正を加えているのでご確認いただけると嬉しいです！
確認後、マージしていただいて大丈夫です！
ありがとうございました🙇

2024-02-26 13:43 UTC, tzptzptzptzptzp approved these changes

2024-03-03 06:19 UTC, merged